### ISSUE TITLE
MacOS version outdated on marketplace + Project failing to compile on Apple Platforms

### ISSUE THREAD

**Issue by albusdemens** [lucoiso/UEHttpGPT#58]
Hello, thank you for sharing this great work! I tested using the plugin on OSX and on Windows 10, and I noticed that on OSX the `HttpGPT Image Generator` option doesn't pop up in the Unreal Editor. I'm running Unreal 5 on both machines. Cheers 

<img width="787" alt="Screen Shot 2023-04-19 at 7 21 08 PM" src="https://user-images.githubusercontent.com/276459/233046771-6f5e325f-08e9-4fe0-afb9-c2b17cc09698.png">

**Comment by lucoiso** [comment]
Hi! :)

Is this occurring with the latest (v1.5.2) version? And there are any warnings or errors related to HttpGPT in the console? :0

Unfortunately I don't have a MacOS machine to test.

**Comment by albusdemens** [comment]
Hello :) What I did was to install the plugin from the Epic Store. That installs version 1.4.7 (see image). I guess a solution could be to upload the plugin on the Store? I will also try to load the plugin manually.

**Comment by albusdemens** [comment]
I also tested downloading the repo zip, unzipping, and placing it in the Plugins folder of the project. This gives the two error messages below. That's why I opted for using the Epic Store instead ;-)
<img width="255" alt="Screen Shot 2023-04-29 at 11 33 09 AM" src="https://user-images.githubusercontent.com/276459/235279668-fa3475fa-6d8e-4330-8c44-0a772cc8accc.png"> 
<img width="249" alt="Screen Shot 2023-04-29 at 11 33 17 AM" src="https://user-images.githubusercontent.com/276459/235279667-f8e6f420-799a-4e8c-96e3-1fa5f92bfdf9.png">

**Comment by lucoiso** [comment]
Ahhh, the epic store version for MacOS is older and doesn't contain the DALL-E module

I removed the iOS and MacOS version from the store because these platforms weren't accepting C++17 features after some implementations. I don't know why this started, because was working well before the DALL-E (and the previous versions already contains some C++17 features lol), but the marketplace team sent me logs containing only "[...] Is a c++17 feature" errors and refused the update.

To use the latest version you'll need to compile the project with C++17

I don't know as well how to do this on MacOS because I never had one xd
But i think you'll just need to open the project settings using XCode and add the -std=c++17 flag in the build options

If any error occurs, feel free to send me the logs to check whats happening

**Comment by lucoiso** [comment]
MacOS wasnt accepting cpp17, will to submit to marketplace again soon.
